### ISSUE TITLE
[PE-D][Tester E] Adding Invalid Email

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-F14-4/tp#172] opened 2024-04-05 21:54 UTC
![SCR-20240405-obgm.png](https://raw.githubusercontent.com/raysonchia/ped/main/files/bf277717-2355-4920-967f-2717a7ae75d0.png)

## Description
The application's current validation system incorrectly accepts email addresses without a top-level domain (TLD), such as `john@example`. According to standard internet email address conventions, a valid email address must include a TLD (e.g., ".com", ".net", ".org"). This oversight could lead to the acceptance of incomplete or incorrect email addresses.

## Steps to Reproduce
1. Enter an email address lacking a TLD into the relevant input field (e.g., using "john@example" as the email address).
2. Submit command that processes the email address.
3. Note that the system accepts the email address without indicating any error.

## Expected Behaviour
The validation system should reject email addresses that do not conform to standard email address conventions, specifically those lacking a TLD. It should prompt the user with an error message indicating the need for a complete email address.

## Suggested Changes
- Enhance the email validation logic to include checks for a TLD in the email address format. This would ensure that all accepted email addresses meet the standard conventions.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: raysonchia/ped#12

**Comment by FangRuoqing** [comment] 2024-04-11 09:38
From forum, "If you app reject a valid email, it's a bug that can be fixed in v1.4. But if the issue is that it also accepts certain invalid emails, it's not eligible to be fixed during the feature freeze. Instead, you can update the UG to match the current behavior (e.g., not mention email validation at all or mention that some level of validation is in place but it is up to the user to ensure the email is valid)."
https://github.com/nus-cs2103-AY2324S2/forum/issues/707

**Closed** 2024-04-11 13:02 UTC
